project_id = "gmlvosodlnhllqbxtoum"

[functions.amg-verify-insurance]
verify_jwt = false

[functions.amg-sync-contracts]
verify_jwt = false

[functions.amg-get-payments]
verify_jwt = false

[functions.amg-get-policy-status]
verify_jwt = false

[functions.holo-init-payment]
verify_jwt = false

[functions.holo-notification]
verify_jwt = false